name: Doc Site
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # transform version e.g. v1.23.4 to 1-23-4
    - name: Get version
      id: publish-version
      run: echo ::set-output name=VERSION::${{ github.ref_name }} | sed 's/v//g' | sed 's/\./-/g'
    
    # echo version
    - name: Echo version
      run: echo ${{ steps.publish-version.outputs.VERSION }}
